apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qg8v3nvbc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qg8v3nvbc-go 
  name: qg8v3nvbc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qg8v3nvbc-go 
